version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "[skip netlify]"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "in_range"
